# Generated by Django 4.1.2 on 2022-11-04 20:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(db_index=True, help_text="Entrer le nom de l'article", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Rajouter des descriptions supplémentaires, ex. volume de la boite')),
                ('prix_achat', models.DecimalField(decimal_places=4, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=4, max_digits=10)),
                ('devise', models.CharField(default='FCFA', max_length=30)),
                ('quantite', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, help_text='Entrer la vente', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('quantite_vente', models.PositiveIntegerField()),
                ('prix_total', models.CharField(editable=False, max_length=30)),
                ('benefice', models.CharField(editable=False, max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conv_articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, help_text="Entrer l'approvisionnement'", max_length=100, primary_key=True, serialize=False, unique=True)),
                ('quantite_approvision', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conv_articles.article')),
            ],
        ),
    ]
